# Generated by Django 3.1.6 on 2021-05-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
