# Generated by Django 3.1.6 on 2021-06-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210531_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='username',
        ),
    ]
