# Generated by Django 3.1.6 on 2021-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210601_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(max_length=150),
        ),
    ]
