# Generated by Django 3.1.6 on 2021-06-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210602_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='picture',
            field=models.ImageField(blank=True, default='find_user.png', null=True, upload_to=''),
        ),
    ]
